spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bong
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  r2dbc:
    host: localhost
    database: bong
    driver: pool
    port: 3306
    protocol: mysql
    url: r2dbc:mysql://localhost:3306/bong # schema 이름을 webflux로 지었음
    username: root
    password: 1234

# 추가 설정 - R2DBC에서 Database로 나가는 쿼리를 보고 싶으면 아래처럼 로깅레벨을 설정해야 함
logging:
  level:
    root: INFO
    sql: TRACE
    web: TRACE
    org.springframework.r2dbc.core: debug


